name: Template Action


on:
  workflow_call:
    inputs:
      text:
        description: The text that will be added to the file.
        required: true
        type: string


jobs:
  add-text:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Add text
        run: |
          echo "Adding text to file"
          file=$(cat file.txt)
          echo "${{inputs.text}}" >> "$file"

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Added text to file"
          add: "$(cat file.txt)"