name: Main Workflow

on:
  push:
    branches:
      - main
jobs:
  call-workflow-2-in-local-repo:
    uses: ./.github/workflows/childworkflow.yml
    with:
      text: "This is the text one time"

  call-workflow-3-in-local-repo:
    uses: ./.github/workflows/childworkflow.yml
    with:
      text: "This is the text two time"